name: Auto Push CI

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to 'master' branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is fetched

      - name: Check if HEAD is ahead of origin/master
        run: |
          git fetch origin master  # Ensure we have the latest origin/master
          
          if [ "$(git rev-list --count origin/master..HEAD)" -gt 0 ]; then
            echo "HEAD is ahead of origin/master, pushing changes..."
            git push origin master
          else
            echo "No new commits to push."
          fi

