name: Simple Java CI Pipeline

on:
  push:
    branches:
      - master  # Runs when you push to the master branch
  pull_request:
    branches:
      - master  # Runs when you create a pull request to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checks out the code from your repository

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the JDK version you want to use
          distribution: 'temurin'  # Use Temurin (AdoptOpenJDK) distribution for JDK

      - name: Compile Java Code
        run: |
          mkdir -p bin  # Create the bin directory to store compiled files
          javac -d bin src/**/*.java  # Compile all Java files in the 'src' folder

      - name: Run Tests (if any)
        run: |
          java -cp bin org.junit.runner.JUnitCore YourTestClass  # Run your tests (replace 'YourTestClass' with your actual test class)

      - name: Archive Results (if needed)
        if: always()  # Always runs this step
        uses: actions/upload-artifact@v3
        with:
          name: test-results  # Name for the artifact
          path: bin/  # Path to store compiled class files or test results

