name: Python CI

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Runs the workflow on the latest Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies

      - name: Run tests with pytest
        run: |
          pytest tests/ --junitxml=report.xml  # Run the tests and generate a report

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.xml  # Upload the generated test report

